//
// Created by ruben on 22/11/23.
//

#ifndef FLOWBETWEENFLATPLATES_COMPUTERECTANGLECENTROID_H
#define FLOWBETWEENFLATPLATES_COMPUTERECTANGLECENTROID_H

#include "../node/Node.h"


Node  computeRectangleCentroid(Node p1, Node p2, Node p3, Node p4);

#endif //FLOWBETWEENFLATPLATES_COMPUTERECTANGLECENTROID_H
